### PR TITLE
fix: return correct NX_BASE SHA for merge_group event

### LINKED ISSUE #140: Unexpected shas for Merge Queues
Hi there,
as also explained here #100 we encounter massive building overhead due to the sha calculation.
What we would expect:
assume you have two PRs queued in the merge queue. Tha latest main build is successful. We would assume that Queue positon '#1' would derive latest main(successful) as base sha. Position '#2' in the queue would derive position '#1' as base sha since it assumes that position '#1' will pass the queue as well. 
image

But what we see is that the base sha is always the git merge-base / the common ancestor. Meaning Position '1#' in the queue builds all changes since the branch was created not taking into account that builds on main might have been successful in the meantime. The same for position '#1' in the queue. See below:
image

Looking at the code we do not understand why git merge-base is used here. It might be a good fall back in case you do not find successful commits on main. Maybe miss ordered inside the if else statement? 
https://github.com/nrwl/nx-set-shas/blob/76907e7e5d3cd17ddb5e2b123389f054bffcdd03/find-successful-workflow.ts#L42-L62

### PR DESCRIPTION
**Pull request by paulo9mv**
**Context**

As reported in #140, the current solution for merge-queue works only when the queue size 1. When more commits are added to the queue, the action keeps setting the same `NX_BASE` for all of them.

**Problem**
When new commits are added to the queue, we expect the `NX_BASE` commit to be the last commit in the queue. However, it sets the last commit in master. _This image from https://github.com/nrwl/nx-set-shas/issues/140#issue-2110155589 represents well the problem._

**Solution proposed**
The `NX_BASE` commit should be main branch HEAD commit when merge-queue has size 1. When size > 1, `NX_BASE` should be the HEAD commit of the last merge branch that current commit is on top of.

Fixes #140

### CODE REVIEW

**Comment by paulo9mv** [comment]
Closed since I couldn't test enough

File: find-successful-workflow.ts [hunk 1]
```diff
@@ -40,23 +40,12 @@ let BASE_SHA: string;
...
-      BASE_SHA = baseResult.stdout;
-    } catch (e) {
-      core.setFailed(e.message);
-      return;
-    }
+  if (['pull_request', 'pull_request_target'].includes(eventName) && !github.context.payload.pull_request.merged) {
+    const baseResult = spawnSync('git', ['merge-base', `origin/${mainBranchName}`, 'HEAD'], { encoding: 'utf-8' });
+    BASE_SHA = baseResult.stdout;
+  } else if (eventName == "merge_group") {
+    const baseResult = spawnSync('git', ['rev-parse', 'HEAD^1'], { encoding: 'utf-8' });
```
Comment (paulo9mv) [inline find-successful-workflow.ts:47]: In merge-queue scenario, base will always be the previous commit in the queue.

**Comment by paulo9mv** [comment]
@mandarini would appreciate your review

**Comment by jordanpowell88** [comment]
> We had to fork to pull in this patch (it's working great for us), it would be nice to get it integrated into the real action at some point soon.

Hey everyone! Sorry for the delay in getting a review on this. We've all been super swamped on other initiatives. Luckily I'm hoping to take a look at this soon

**Review by meeroslav — APPROVED** [review]
